### ISSUE TITLE
前端文件是不是有缺失？

### ISSUE THREAD

**Issue by chentongxue** [douban/code#105]
GET http://192.168.1.103:8000/static/js/mod/register.js 404 (Not Found)
GET http://192.168.1.103:8000/static/js/mod/vendors.js 404 (Not Found)
GET http://192.168.1.103:8000/static/js/mod/login.js 404 (Not Found)

**Comment by mozillazg** [comment]
@chentongxue 需要先编译生成静态文件：

```
npm run build
grunt ozma compass:dev
```

**Comment by dongweiming** [comment]
@chentongxue @mozillazg 这个需要执行

```
node_modules/.bin/webpack --progress --colors --watch
```

假如你使用了supervisor都会自动跑起来的. 我现在把dist先加进来了 看看能不能顺利跑起来?
