### ISSUE TITLE
关于 CODE 开源版本

### ISSUE THREAD

**Issue by qingfeng** [douban/code#26]
这次开源之后，就已经吸引这么多朋友开始发PR了，这个说实话我们自己也是始料未及的。所以当前这个开源版本可能得做一个说明。

很多朋友可能也发现了，现在开源出来的版本和豆瓣内部使用的版本差距是非常大的，这是因为此次开源的版本，实际上只是一个希望可以让大家统一开发环境的版本，并且借助这个开源版本，把之前的代码进行一次迁移，所以这个过程应该会花一些时间。

所以，我觉得在初期可以分为以下几件事情来做，可以快速看到效果:

- 一个方便的git server，一个命令就可以启动
- 一个统一的开发环境，方便进行开发环境的搭建和部署，这件事在一开始做是有好处的
- 前端脚手架的搭建，这次开源版本的一个重要目标就是把UI和API进行分离

抛砖引玉 :beer:

**Comment by jumping** [comment]
开源版本能否开放更多的功能？现在的版本功能比较少。

**Comment by kxxoling** [comment]
好不容易部署成功了，结果发现功能太少了。我们刚从 BitBuckt 迁移到了自己搭建的 Kallithea（支持 Hg），虽然丑了点但是功能比现在开源的这个 Code 强多了！

**Comment by xtao** [comment]
抱歉，后续开发没有跟上。。。

--
XTao

2015-03-13 14:02 GMT+08:00 Kane Blueriver <notifications@github.com>:

**Comment by kxxoling** [comment]
@xtao 那还打算继续开源吗？＝。＝

**Comment by yishilin** [comment]
此项目已死， 
* 最后的一次代码checkin是在2014年3月

https://github.com/douban-code/douban-code.github.io/graphs/code-frequency

**Comment by dongweiming** [comment]
唉 好可惜

**Comment by kxxoling** [comment]
有时间等 CODE 发布，不如用 GitLab CE，也提供 CI 支持。

**Comment by laiwei** [comment]
@flycondor 这个还会有下一步么

**Comment by dongweiming** [comment]
@laiwei 我会继续下一步 更详细的可以看 https://github.com/douban/code/issues/65

**Comment by dongweiming** [comment]
@yishilin  @kxxoling @jumping  @jarvys 相信很快 功能就会全部先铺出来. 供大家试用

**Comment by sup4r** [comment]
@dongweiming hi、项目开源还在进展吗? 或许我们也可以参与进来，加快速度。

**Comment by dongweiming** [comment]
@sup4r @qingfeng 

ALL! CODEv1 已经放出来 https://github.com/douban/code/pull/68 欢迎来参与. 稍后我会做一个vagrant/docker的可用虚拟机, 也会完善初始化配置的文档和脚本

**Comment by dongweiming** [comment]
现在CODE已经里程碑的放出来了. 开启下一个阶段
