### ISSUE TITLE
创建project以后要重启服务才能push成功

### ISSUE THREAD

**Issue by davideuler** [douban/code#36]
创建project以后，push代码不成功。

$ git remote add origin http://192.168.8.98:8001/david/demo.git
$ git push -u origin master
fatal: unable to access 'http://192.168.8.98:8001/david/demo.git/': The requested URL returned error: 500

kill gunicorn进程，重新启动，可以push成功。

$ git push -u origin master
Counting objects: 20, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (20/20), 2.51 KiB | 0 bytes/s, done.
Total 20 (delta 2), reused 0 (delta 0)
To http://192.168.8.98:8001/david/demo.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.

服务器：centos 6.3, python 2.7.3
客户端：mac 10.9.1

**Comment by dongweiming** [comment]
@davideuler 欢迎再试
