### ISSUE TITLE
做个docker镜像吧

### ISSUE THREAD

**Issue by greatqn** [douban/code#60]
试着运行了下安装脚本，国内这个网络条件下，还没能完整跑完的。

做个docker镜像发布出来。这样可以跳过繁琐的安装，直接尝尝鲜。

之前看过PPT，说这东西挺好，但还没完全理解它的运作机制。

**Comment by dongweiming** [comment]
@greatqn @CMGS @crystaldust @kebot @tobegit3hub 现在CODE继续. https://github.com/douban/code/pull/67 合并后 docker环境应该可用. 有问题 欢迎继续pr/issue

**Comment by qingfeng** [comment]
前端有打算用react吗～

**Comment by dongweiming** [comment]
@qingfeng 有. 我现在的工作也逐渐往前端上转.

**Comment by qingfeng** [comment]
👍期待react

**Comment by dongweiming** [comment]
ALL! CODE已经放出来了, https://github.com/douban/code/pull/68 欢迎一起来改进.

**Comment by dongweiming** [comment]
现在已经有了vagrant的源, 之后我会做了code的源
