### ISSUE TITLE
不再更新维护了？

### ISSUE THREAD

**Issue by sdgdsffdsfff** [douban/code#65]
不再更新维护了？

**Comment by dongweiming** [comment]
@sdgdsffdsfff 感谢你的关注. 未来的code我会继续更新维护.

**Comment by qingfeng** [comment]
👍

**Comment by seansay** [comment]
:clap:

**Comment by osDanielLee** [comment]
Great!

**Comment by eclipselu** [comment]
:100:

**Comment by dongweiming** [comment]
我在这里统一回复下吧.

各位 watchers

我会把这个项目做完 - 做完的标准的是开源版本和豆瓣正在用的版本功能上一样

原因:

1. CODE是一个非常有价值有意义的开源项目
2. CODE是豆瓣工程师文化的结晶
3. 我对CODE还有很多想法想实践出来. 也欢迎大家来填坑, 把新的想法实现出来或者提issue 

目前看来基本是我一个人利用业余时间, 而CODE是一个在豆瓣高速迭代开发历时2年, 目前以及较稳定的跑了4年, 贡献者差不多一百人的大项目. 这个过程可以预计会略长, 所以早期大家可以策略性的选择对CODE开发的消息关注/取关/忽略. 

以下是一些我的想法:

* 因为人力有限, 我准备先出一个可用的版本. 所以暂时web框架还使用quixote. 未来有机会可以替换掉flask(或者说一定会替换掉). 前端用到的库也暂时不变化 - 早期也是让我熟悉的过程
* 我会先做从豆瓣的环境剥离, 为了尽量不使用豆瓣原有的一些基础库. 需要去实现很多东西.
* 然后是重构. 对于目前遇到的坑, 能够看到的代码用法以及性能上都会重构
* 基于当时的技术条件, 现在看起来有些东西可能有更好的替代品或者其他的解决方案. 我也会在重构的时候尽量让它不落后.


和大家共勉..

**Comment by xtao** [comment]
:clap:

**Comment by hanxi** [comment]
:+1:

**Comment by ithinco** [comment]
:beer:

**Comment by kdwycz** [comment]
:+1:

**Comment by dongweiming** [comment]
@sdgdsffdsfff 

ALL! CODEv1 已经放出来 https://github.com/douban/code/pull/68

**Comment by menghan** [comment]
:+1:

**Comment by CNBorn** [comment]
@dongweiming 建议：是否可以考虑关闭这个Issue了？理由：体验问题，现在这个Repo介绍信息还不友好（比如Github短说明和Readme.md里居然都没能说明白这个Repo是做什么的，只有看了.github.io那个页面才能找到中文的介绍），而且用户需要读这个标题为“不再更新维护”的Issue才能了解到这个Repo“是在更新维护的”，太辛苦…… 

建议把这个Issue里的一些有用信息有选择性地移到README里面（比如部分截图），然后清理/回复/关闭一下不再有时效性的PR/Issues 并给出一个简单下一步计划/如何贡献的指南（现阶段甚至都不必非得是英语），这就已经超越之前豆瓣所有的开源项目的水平了。

P.S. Sorry用这么PM的视角来看这个，不过能上Github Trending实在太赞了！也希望能趁机吸引更多的朋友来贡献啊

**Comment by dongweiming** [comment]
@CNBorn 好 我一会建个issue 发一下我的考虑

**Comment by sqrabs** [comment]
:beers:
