### ISSUE TITLE
emoji表情肿么办

### ISSUE THREAD

**Issue by dongweiming** [douban/code#70]
@xtao @qingfeng @CNBorn @hongqn 

大神们... 邢老师提到 CODE用到的图片可能有版权问题. 看起来大部分图片都是你们贡献的. 我google图片搜索了下都没有明显看到这些图(抑或是自己生成的?). 所以先来问问那些图我可以放出来, 那些图我不应该放出来?

**Comment by xtao** [comment]
可以考虑用 https://github.com/Genshin/PhantomOpenEmoji 替换全部。

**Comment by qingfeng** [comment]
emoji也是有版权的？那个不是系统自带的吗。。。？

**Comment by qingfeng** [comment]
查了一下确实是有版权，建议更换
GitLab好像还为此删除过一次 https://ruby-china.org/notes/1709

**Comment by dongweiming** [comment]
@qingfeng LGTM也不能留么.. 好哀伤

**Comment by qingfeng** [comment]
LGTM应该没事吧？那个我记得是教授自己做的图片阿？

**Comment by dongweiming** [comment]
现在放了3种emoji

1. https://github.com/Ranks/emojione 
2. https://github.com/wpeterson/emoji 它是基于https://github.com/Genshin/PhantomOpenEmoji的
3. https://github.com/twitter/twemoji/ 

然后添加了lgtm和ruby.

先用着.

**Comment by CNBorn** [comment]
@dongweiming 补充（虽然不是Emoji），Repo里好像还有Foursquare的Badge图片，需要确认下那些是否有版权要求，否则应该一并删除

**Comment by CNBorn** [comment]
@dongweiming 结论是需要删除badge相关图片 ref: https://www.quora.com/Does-foursquare-have-trademark-protection-for-badge/answer/Stasys-Drazdauskas

**Comment by dongweiming** [comment]
@CNBorn 收到~

**Comment by dongweiming** [comment]
只能先删了. 等待CODE的设计师啦
